
# download build env files
FROM alpine:latest as builder
ARG dsm_version=7.2
RUN apk --no-cache add curl
RUN mkdir -p /tmp/build_env \
	&& curl -L https://archive.synology.com/download/ToolChain/toolkit/{dsm_version}/base_env-${dsm_version}.txz | tar xzJ -C /tmp/build_env

# create build env
FROM scratch
COPY --from=builder /tmp/build_env /

